class dict_answers:
    FONOLOGIA = {
        'q1' : 'Letra A)',
        'q2' : 'Letra D)',
        'q3' : 'Letra B)',
        'q4' : 'Letra A)',
        'q5' : 'Letra B)',
        'q6' : 'Letra A)',
        'q7' : 'Letra C)',
        'q8' : 'Letra B)',
        'q9' : 'Letra C)',
        'q10' : 'Letra A)',
        'q11' : 'Letra B)',
        'q12' : 'INCORRETO',
        'q13' : 'Letra C)',
        'q14' : 'Letra D)',
        'q15' : 'ERRADO',
        'q16' : 'CERTO',
        'q17' : 'Letra C)',
        'q18' : 'Letra C)',
        'q19' : 'Letra D)',
        'q20' : 'Letra D)',
        'q21' : 'Letra C)',
        'q22' : 'Letra B)',
        'q23' : 'Letra A)',
        'q24' : 'Letra C)',
        'q25' : 'Letra A)',
        'q26' : 'Letra E)',
        'q27' : 'Letra B)',
        'q28' : 'Letra E)',
        'q29' : 'Letra D)',
        'q30' : 'Letra E)',
        'q31' : 'Letra B)',
        'q32' : 'I - CORRETA\nII - INCORRETA',
        'q33' : 'Letra B)',
        'q34' : 'Letra B)',
        'q35' : 'Letra D)',
        'q36' : 'Letra B)',
        'q37' : 'Letra B)'
    }
    RANGE_THEMES= {
        (1,37): 'fonologia',
        (1,37): 'ortografia',
        (1,37): 'acentuacao_grafica', 
        (1,37): 'semantica_lexicologia',
        (1,37): 'morfologia',
        (1,37): 'formacao_palavras' ,
        (1,37): 'substantivo' ,
        (1,37): 'adjetivo' ,
        (1,37): 'artigo' ,
        (1,37): 'numeral' ,
        (1,37): 'pronome' ,
        (1,37): 'verbo' ,
        (1,37): 'adverbio' ,
        (1,37): 'preposicao' ,
        (1,37): 'conjuncao' ,
        (1,37): 'interjeicao' , 
        (1,37): 'sintaxe' ,
        (1,37): 'frase_oracao_periodo' ,
        (1,37): 'termos_essenciais_oracao' ,
        (1,37): 'termos_integrantes_oracao' , 
        (1,37): 'termos_acessorios_oracao' ,
        (1,37): 'oracoes_coordenadas' ,
        (1,37): 'oracoes_subordinadas' ,
        (1,37): 'oracoes_reduzidas',
        (1,37): 'oracoes_intercaladas',
        (1,37): 'periodo_misto',
        (1,37): 'pontuacao',
        (1,37): 'concordancia',
        (1,37): 'regencia',
        (1,37): 'que_se_como',
        (1,37): 'estilistica',
        (1,37): 'teoria_comunicacao',
        (1,37): 'compreensao_interpretacao_texto_tipologia_textual',
        (1,37): 'coesao_coerencia',
        (1,37): 'dominio_registro_culto',
        (1,37): 'reescritura_frases',
        (1,37): 'questoes_comentadas_banca_cqip'
    }




DICT_CHAPTER_THEMES = {
        1  : dict_answers.FONOLOGIA,
        2  : 'ortografia',
        3  : 'acentuacao_grafica', 
        4  : 'semantica_lexicologia',
        5  : 'morfologia',
        6  : 'formacao_palavras' ,
        7  : 'substantivo' ,
        8  : 'adjetivo' ,
        9  : 'artigo' ,
        10 : 'numeral' ,
        11 : 'pronome' ,
        12 : 'verbo' ,
        13 : 'adverbio' ,
        14 : 'preposicao' ,
        15 : 'conjuncao' ,
        16 : 'interjeicao' , 
        17 : 'sintaxe' ,
        18 : 'frase_oracao_periodo' ,
        19 : 'termos_essenciais_oracao' ,
        20 : 'termos_integrantes_oracao' , 
        21 : 'termos_acessorios_oracao' ,
        22 : 'oracoes_coordenadas' ,
        23 : 'oracoes_subordinadas' ,
        24 : 'oracoes_reduzidas',
        25 : 'oracoes_intercaladas',
        26 : 'periodo_misto',
        27 : 'pontuacao',
        28 : 'concordancia',
        29 : 'regencia',
        30 : 'que_se_como',
        31 : 'estilistica',
        32 : 'teoria_comunicacao',
        33 : 'compreensao_interpretacao_texto_tipologia_textual',
        34 : 'coesao_coerencia',
        35 : 'dominio_registro_culto',
        36 : 'reescritura_frases',
        37 : 'questoes_comentadas_banca_cqip'
        }

def dict_choose_options(user_answer:int): 
    if user_answer in DICT_CHAPTER_THEMES:
        choose_dict = dict(DICT_CHAPTER_THEMES[user_answer])
        return choose_dict
    return None

